version: "3"

services:
  autossh_https_to_frog:
    image: jnovack/autossh
    environment:
      - SSH_REMOTE_USER=frog
      - SSH_REMOTE_HOST={{ hostvars['frog'].ansible_host }}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=8443
      - SSH_TARGET_HOST=localhost
      - SSH_TARGET_PORT=8443
      - SSH_KEY_FILE=/id_ed25519
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/pi/.ssh/id_ed25519:/id_ed25519

  autossh_http_to_frog:
    image: jnovack/autossh
    environment:
      - SSH_REMOTE_USER=frog
      - SSH_REMOTE_HOST={{ hostvars['frog'].ansible_host }}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=8080
      - SSH_TARGET_HOST=localhost
      - SSH_TARGET_PORT=8080
      - SSH_KEY_FILE=/id_ed25519
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/pi/.ssh/id_ed25519:/id_ed25519

  autossh_syncthing_to_frog:
    image: jnovack/autossh
    environment:
      - SSH_REMOTE_USER=frog
      - SSH_REMOTE_HOST={{ hostvars['frog'].ansible_host }}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=22000
      - SSH_TARGET_HOST=localhost
      - SSH_TARGET_PORT=22000
      - SSH_KEY_FILE=/id_ed25519
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/pi/.ssh/id_ed25519:/id_ed25519
