services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: "Europe/Warsaw"
      DNSMASQ_LISTENING: "all"
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_etc_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped

volumes:
  pihole_etc:
  pihole_etc_dnsmasq:
