services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - homeassistant_config:/config
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0
    network_mode: host
    privileged: true
    restart: unless-stopped

volumes:
  homeassistant_config:
