services:
  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - URL=damiankoper.dev
      - SUBDOMAINS=ha,actual,n8n,syncthing,immich
      - VALIDATION=http
      - EMAIL=kopernickk@gmail.com #optional
      - ONLY_SUBDOMAINS=true #optional
    volumes:
      - swag_config:/config
    ports:
      - 8443:443
      - 8080:80
    restart: unless-stopped

volumes:
  swag_config:
