services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD={{ immich_db_password }}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - immich_appdata:/config
      - /mnt/homelab_seagate/homelab/immich:/photos
      - /mnt/homelab_seagate/homelab/immich_import:/import:ro #optional
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={{ immich_db_password }}
      - POSTGRES_DB=immich
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  immich_appdata:
  postgres_data:
