version: "3"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Warsaw"
    volumes:
      - "syncthing_config:/config"
      - "/mnt/homelab_seagate/homelab/sync:/data"
    ports:
      - "22000:22000/tcp"
      - "22000:22000/udp"
    restart: unless-stopped

volumes:
  syncthing_config:
