services:
  autossh_https_to_frog:
    image: jnovack/autossh
    restart: unless-stopped
    network_mode: host
    deploy:
      placement:
        constraints:
          - "node.hostname==homelab-alfa"
    environment:
      - SSH_REMOTE_USER=frog
      - SSH_REMOTE_HOST={{ hostvars['frog'].ansible_host }}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=8443
      - SSH_TARGET_HOST=127.0.0.1
      - SSH_TARGET_PORT=8443
      - SSH_KEY_FILE=/id_ed25519
    volumes:
      - /home/pi/.ssh/id_ed25519:/id_ed25519
    networks:
      - outside

  autossh_http_to_frog:
    image: jnovack/autossh
    restart: unless-stopped
    network_mode: host
    deploy:
      placement:
        constraints:
          - "node.hostname==homelab-alfa"
    environment:
      - SSH_REMOTE_USER=frog
      - SSH_REMOTE_HOST={{ hostvars['frog'].ansible_host }}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=8080
      - SSH_TARGET_HOST=127.0.0.1
      - SSH_TARGET_PORT=8080
      - SSH_KEY_FILE=/id_ed25519
    volumes:
      - /home/pi/.ssh/id_ed25519:/id_ed25519
    networks:
      - outside

  autossh_syncthing_to_frog:
    image: jnovack/autossh
    restart: unless-stopped
    network_mode: host
    deploy:
      placement:
        constraints:
          - "node.hostname==homelab-alfa"
    environment:
      - SSH_REMOTE_USER=frog
      - SSH_REMOTE_HOST={{ hostvars['frog'].ansible_host }}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=22000
      - SSH_TARGET_HOST=127.0.0.1
      - SSH_TARGET_PORT=22000
      - SSH_KEY_FILE=/id_ed25519
    volumes:
      - /home/pi/.ssh/id_ed25519:/id_ed25519
    networks:
      - outside
