services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==homelab-alfa"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD={{ immich_db_password }}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /mnt/homelab_zfs/homelab/immich_appdata:/config
      - /mnt/homelab_zfs/homelab/immich_photos:/photos
      - /mnt/homelab_zfs/homelab/immich_import:/import:ro #optional
    networks:
      - overlay
      - bridge

  redis:
    image: redis
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==homelab-alfa"
    networks:
      - overlay

  postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==homelab-alfa"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={{ immich_db_password }}
      - POSTGRES_DB=immich
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - overlay

volumes:
  postgres_data:
