services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==homelab-bravo"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: "Europe/Warsaw"
      DNSMASQ_LISTENING: "all"
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_etc_dnsmasq:/etc/dnsmasq.d
    networks:
      - bridge

volumes:
  pihole_etc:
  pihole_etc_dnsmasq:
